syntax = "proto3";
package services.inner.notification;
option go_package = "github.com/scrynaxx/tr-core/generated/services/inner/notification;notification";

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "google/api/annotations.proto";

service NotificationService {
  rpc SendEmail(SendEmailRequest) returns (google.protobuf.Empty);
}

message SendEmailRequest {
  string subject = 1 [(buf.validate.field).string = {min_len: 1, max_len: 255}];
  string body = 2 [(buf.validate.field).string = {min_len: 1}];
  repeated string receivers = 3 [(buf.validate.field).repeated = {min_items: 1}];
}
